.travis.yml
bin/test
tests/test-login.js

Add automated tests based on chimp, mocha, chai and travis-ci

---

.meteor/packages
.meteor/versions
bin/test
packages/prng/package.js
packages/prng/prng.js
server/testing.createnload.data.js
settings.ci.json
tests/test-course-list.js

Add a seedable pseudo number generator for test purposes

---

client/start.js
client/views/courses/details/course.details.js
client/views/courses/edit/course.edit.js
client/views/courses/members/course.members.js
collections/courses.js
collections/roles.js
server/publications.js
server/updates/2016.08.23 removeRoles.js

I propose just removing the Roles collection altogether. The small count of roles does not justify having a collection when we can define the list with a few lines of code like its done now. We can just use this list directly.

Use static list of roles instead of collection

---

client/views/navigation/navbar/navbar.html
client/views/navigation/navbar/navbar.js

Quick fix for #537. I think creating a separate route "createEvent" would be the proper solution, but we would have to shove a lot of code around. So for the moment I think having this fix is preferable.

make create menu active when creating an event

---

client/lib/mfFixedTranslations.html
client/views/courses/details/course.details.js
client/views/courses/discussion/course.discussion.js
client/views/courses/edit/course.edit.js
client/views/courses/members/course.members.js
client/views/events/details/event.details.js
client/views/events/edit/event.edit.js
client/views/groups/details/group.details.js
client/views/groups/settings/group.settings.js

Success messages are simplified to only three statements, 'saved', 'added' and 'removed'. Maybe some messages could fit better to the according action? #459

Simplified success messages

---

client/views/venues/edit/venue.edit.html

Venue edit message

---

client/views/events/editLocation/_event.editLocation.scss
client/views/events/editLocation/event.editLocation.html

thanks to Luca (he told me to do the hot fix before :-))

adds create venue button at edit event + info message, closes #639

---

client/views/frames/calendar/_frame.calendar.scss
client/views/frames/calendar/frame.calendar.html
client/views/frames/calendar/frame.calendar.js

Add feature to change calendar frame css-properties via URL query

Change calendar frame css-properties via URL query

---

client/styles/_components.scss
client/styles/components/_list-style.scss
client/views/frames/calendar/_frame.calendar.scss
client/views/frames/calendar/frame.calendar.html
client/views/frames/calendar/frame.calendar.js
client/views/frames/list/_frame.list.scss
client/views/frames/list/frame.list.html
client/views/frames/list/frame.list.js

The style is as well applied to the Course-List frame (.../frame/list). Every course has now foldable information added.
A todo is the integration of changeable color styles within the URL, like in the calendar frame (.../frame/calendar).

global list-style from .../frame/calendar style

---

client/views/courses/members/_course.members.scss
client/views/courses/members/course.members.html
client/views/courses/members/course.members.js

a problem could be, that the confirm dialog decision can be saved for all confirm dialogs: #695

Remove user button: design and confirm dialog

---

client/views/courses/members/_course.members.scss
client/views/courses/members/course.members.html
client/views/courses/members/course.members.js

again changed design to fit in another confirm dialog
#695

Remove user from team button

---

client/lib/client.functions.js
client/views/courses/edit/course.edit.html
client/views/courses/edit/course.edit.js
client/views/events/edit/event.edit.html
client/views/events/edit/event.edit.js
client/views/groups/details/group.details.html
client/views/groups/details/group.details.js
client/views/groups/settings/group.settings.html
client/views/groups/settings/group.settings.js
client/views/venues/edit/venue.edit.html
client/views/venues/edit/venue.edit.js
client/widgets/buttons/buttons.html
client/widgets/buttons/buttons.js

Disable save buttons when saving and change icon and text accordingly.

Disable save buttons when saving

---

client/styles/_bootstrap.scss
client/styles/_components.scss
client/styles/components/_modals.scss
client/views/login/frame/_login.frame.scss
client/views/login/frame/login.frame.html
client/views/login/frame/login.frame.js
client/views/login/menu/login.menu.html
client/views/main.html

A solution to #611. Having a pop-up dialog (in this case a bootstrap 'modal') seemed the most intuitive.

Use modal dialog for creating an account

---

collections/courses.js

translation for "has proposed course" text

---

client/views/events/edit/event.edit.html
client/views/events/edit/event.edit.js
collections/events.js
imports/Notification.js
private/mails/notificationEventMail.html

After editing an event, notifications can be sent to the course members. With this change the organiser can add a personal message to these notifications.
- is it ok to pass the personal message from the html form all the way to event.edit.js, event.js, Notifications.js and finally to notificationEventMail.html?
- maybe the input text field should be bigger, maybe it should be an editable field
- the presentation of the message in the email should maybe be different...

personal notification message

---

client/views/courses/members/_course.members.scss
client/views/courses/members/course.members.html
client/views/courses/members/course.members.js

No issue here but a small detail that bugged me for a while now..
Sort course members my amount of roles (excluding participant role) and limit them to 10 displayed. Add a button to increase displayed members by 10 until all members are listed.

Sort members

---

client/views/courses/discussion/_course.discussion.scss
client/views/courses/discussion/course.discussion.html
client/views/courses/discussion/course.discussion.js

Inspired by #770 I limited the displayed comments to 3 with maximum 1 answer each by default.

limit displayed comments (and answers)

---

LICENSE

Byte correct AGPL License file, so GitHub will recognize it

---

client/views/groups/list/_group.list.scss
client/views/navigation/navbar/_navbar.scss
client/views/regions/regions.html
client/views/regions/splash/_regions.splash.scss
client/views/regions/splash/regions.splash.html
client/views/regions/splash/regions.splash.js

add option to login from region splash

---

client/views/venues/details/venue.details.html

Deleted the "time created", etc. from the venues' description.

---

client/views/courses/edit/course.edit.html
client/views/courses/edit/course.edit.js
client/views/find/find.js

solves an issue inside a comment of #483

Adds group name in new course when in group

---

.jshintignore
.jshintrc
.travis.yml
client/lib/client.functions.js
client/views/frames/schedule/schedule.js
client/views/groups/details/group.details.js
client/views/log/showLog.js
client/views/static/translate/translate.info.js
client/views/venues/details/venue.details.js
client/widgets/editable/helpers.js
client/widgets/editable/lib.js
collections/users.js
imports/Api.js
imports/IpLocation.js
imports/Profile.js
imports/RegionSelection.js
imports/StringTools.js
imports/collections/Log.js
imports/notification/Notification.Comment.js
imports/notification/Notification.Event.js
imports/notification/Notification.Join.js
imports/notification/Notification.PrivateMessage.js
imports/notification/Notification.js
imports/startup/api.json.js
lib/Filtering.js
package.json
packages/prng/package.js
packages/prng/prng.js
server/updates/2017.05.08 providedEmail.js

* Add jshint as a dev-dependency
* Add an npm script which runs jshint
* Fix all jshint errors (mostly semicolons)

928 feature run jshint on travis

---

.jshintrc
.meteor/packages
.meteor/versions
client/views/calendar/calendar.js
client/views/courses/create/course.create.js
client/views/find/find.js
client/views/frames/calendar/frame.calendar.js
client/views/frames/events/frame.events.js
client/views/frames/list/frame.list.js
client/views/frames/propose/frame.propose.js
client/views/frames/week/frame.week.js
client/views/kiosk/kiosk.js
client/views/log/showLog.js
client/views/static/translate/translate.info.js
client/views/venues/map/venue.map.js
imports/Metatags.js
routing.js

Also kill the `webpagename` global variable.

Add opengraph/twitter metadata on all pages

---

client/lib/client.functions.js
client/styles/_bootstrap-variables.scss
client/views/frames/propose/frame.propose.html
client/views/frames/propose/frame.propose.js
client/views/login/frame/_login.frame.scss
client/views/login/frame/login.frame.html
client/views/login/frame/login.frame.js
client/views/login/menu/login.menu.html
client/views/login/menu/login.menu.js
client/views/main.html
imports/ui/account/accountTools.js

Make login (and password recovery) modal too

---

client/views/courses/edit/course.edit.html
client/views/courses/edit/course.edit.js
client/views/frames/propose/frame.propose.html
client/views/frames/propose/frame.propose.js
collections/courses.js

This enables selecting the region in the course proposal frame

1004 region query

---

client/views/courses/edit/course.edit.html
client/views/courses/edit/course.edit.js
client/views/frames/propose/frame.propose.html
client/views/frames/propose/frame.propose.js

This was named `groups` before, now you do openki.net/frame/propose?group=cbdec314ab This patch also removes the old logic.

Rename group param

---

client/views/static/FAQ/markup/FAQ.en.md

It is not ready but "OK" if noone manages to work on this before Tuesday. So, I create the pull request and I will be able to work more on this toward the end of this coming week.

1001 faq english

---

imports/ui/components/courses/members/course-members.js

show "show next 10 participants" only if particpants are more than 10

---

imports/ui/components/courses/members/course-members.html
imports/ui/components/courses/members/course-members.js

Fixes #1101 (not sure if it is the most elegant way but it seems to work)

corrected bug with empty message not being possible to update. 

---

imports/ui/components/courses/roles/course-roles.html
imports/ui/components/courses/roles/course-roles.js

info icon to "toggle" between show/not show the showFirstSteps message

---

imports/notification/Notification.Event.js
private/mails/notificationEventMail.html

Note that I didn't check how it looks (how do we do this easily with e-mails?) but hopefully it is easy to correct.

added links to course and event in notification e-mail 

---

collections/categories.js

added 'education' category to misc re: issue #1067 via @panosnethood

added 'education' category to misc re: issue #1067

---

imports/Api.app-test.js

I added a few test cases to the JSON-API test suite.

Added more API-Testcases

---

imports/notification/notification.comment.js

I don't like how the logic in that file is ballooning. But I didn't want to think and refactor either.

send comment notifications to all in thread

---

imports/utils/html-tools.js
imports/utils/html-tools.test.js

solves issue #1198 (some extreme URL cases might not work)

turns URL in private messages to hyperlinks

---

imports/startup/both/routes.js
imports/ui/components/featured-group/featured-group.html
imports/ui/components/featured-group/featured-group.js
imports/ui/layouts/app-body.html

also show banner once group is loaded and not before. Fixes #1201.

remove path logic from featuredGroup template

---

private/mails/notificationEventMail.html

show the organizers message above the event
